19 create function data download
inbo/ClimateCastR pull request #29
Opened 2024-08-02 15:34 UTC by soriadelva

The original idea was to create a function data_download with the same functionality + some extras as the code used in the climate_match script. However, as the input could be either a (vector of) taxonkey(s), a zipfile, or a downloadkey, and these should better not be combined (i.e., it may be confusing to provide both taxonkeys and a zipfile, especially since the zipfile would allow to upload data that may be different from the usual GBIF download as long as the necessary columns are present), I decided to create three seperate functions, one for each type of data download/import. As such, it will also be very clear what the necessary input of each function is (i.e., either taxonkeys, a zipfile, or a downloadkey).

2024-08-02 20:26 UTC, soriadelva commented
It's weird that the checks fail, Devtools::check() did nog signal any errors 🤔

2024-08-05 13:15 UTC, SanderDevisscher requested changes

2024-08-05 13:15 UTC, SanderDevisscher commented on R/get_data.R
> +#' utils::download.file(url, zipfile, mode = "wb")
I get the following error when downloading the shape:
```
Warning message:
In utils::unzip(zipfile, exdir = tempdir()) :
  error 1 in extracting from zip file
```

probably its a missing package I'll investigate.

2024-08-05 13:31 UTC, SanderDevisscher commented on R/get_data.R
> +#' utils::download.file(url, zipfile, mode = "wb")
use this url: url <- "https://zenodo.org/api/records/3386224/files-archive"

2024-08-07 10:54 UTC, SanderDevisscher requested changes
Just some small changes and I can approve

2024-08-07 10:54 UTC, SanderDevisscher commented on tests/testthat/test-get_data.R
this file is empty ?

2024-08-07 10:54 UTC, SanderDevisscher commented on R/get_data.R
> +#' get_gbif_data(taxon_key)
@soriadelva any reason you don't store the result of these steps in the environment ? ea add `df <-` ?

2024-08-07 15:25 UTC, soriadelva commented on tests/testthat/test-get_data.R
Will make the tests in the future, but created the file already

2024-08-08 08:19 UTC, SanderDevisscher approved these changes
good work

2024-08-08 08:19 UTC, merged