fix #30
inbo/ClimateCastR pull request #31
Opened 2024-08-05 14:02 UTC by SanderDevisscher

fixes #30

2024-08-06 07:23 UTC, soriadelva approved these changes

2024-08-06 07:39 UTC, soriadelva requested changes
Run devtools::document() again

2024-08-07 10:04 UTC, SanderDevisscher commented
@soriadelva can you approve ?

2024-08-07 10:08 UTC, soriadelva approved these changes

2024-08-07 10:11 UTC, merged